# Dependencies
markdown:         redcarpet
highlighter:         true

# Permalinks
permalink:        pretty

# Setup
title:            CK Tan
tagline:          'Bits in Rapid Transit'
description:      'Blog on Data, Postgres, SQL, BI, etc.'
url:              http://cktan.us/

author:
  name:           'CK Tan'
  url:            https://twitter.com/cktan

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/lanyon
