# Dependencies
markdown:         redcarpet


# Permalinks
permalink:        pretty

# Setup
title:            CK Tan
tagline:          'Data and such'
description:      'Data and such'
url:              http://cktan.us/

author:
  name:           'CK Tan'
  url:            https://twitter.com/cktan

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/cktan
